version: '3.3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: mcyangdb
      MYSQL_USER: mcyang
      MYSQL_PASSWORD: mcyang
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
        - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mcyangdb
      - DB_USER=mcyang
      - DB_PASSWORD=mcyang

volumes:
  db_data: