version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: mcyangdb
      MYSQL_USER: mcyang
      MYSQL_PASSWORD: mcyang
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
  web:
    build:
      dockerfile: Dockerfile
#    command:
#      - python manage.py migrate && python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mcyangdb
      - DB_USER=mcyang
      - DB_PASSWORD=mcyang
volumes:
  db_data:
