# Generated by Django 4.0.7 on 2022-09-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McyangCourse',
            fields=[
                ('C_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('C_name', models.TextField(max_length=30)),
                ('C_image', models.ImageField(upload_to='img_course/')),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mc_course',
            },
        ),
        migrations.CreateModel(
            name='McyangRaceAnswer',
            fields=[
                ('R_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('R_doc', models.TextField(max_length=255)),
                ('Status', models.BooleanField(default=True)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangcourse')),
            ],
            options={
                'db_table': 'mc_raceanswer',
            },
        ),
        migrations.CreateModel(
            name='McyangSign',
            fields=[
                ('Sign_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangcourse')),
            ],
            options={
                'db_table': 'mc_sign',
            },
        ),
        migrations.CreateModel(
            name='McyangStudent',
            fields=[
                ('S_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('S_name', models.TextField(max_length=30)),
                ('S_email', models.CharField(max_length=50, unique=True)),
                ('S_password', models.TextField(max_length=50)),
                ('S_image', models.ImageField(upload_to='img_student/')),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mc_student',
            },
        ),
        migrations.CreateModel(
            name='McyangTeam',
            fields=[
                ('T_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Group_number', models.IntegerField(null=True)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('Leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangstudent')),
            ],
            options={
                'db_table': 'mc_team',
            },
        ),
        migrations.CreateModel(
            name='McyangTeamMember',
            fields=[
                ('TM_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Team_number', models.IntegerField(null=True)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangstudent')),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangteam')),
            ],
            options={
                'db_table': 'mc_teammember',
            },
        ),
        migrations.CreateModel(
            name='McyangTeamDesc',
            fields=[
                ('TD_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('TD_doc', models.TextField(max_length=255)),
                ('TD_total', models.IntegerField()),
                ('TD_limit', models.IntegerField()),
                ('TD_status', models.IntegerField(null=True)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangcourse')),
            ],
            options={
                'db_table': 'mc_teamdesc',
            },
        ),
        migrations.AddField(
            model_name='mcyangteam',
            name='TD_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangteamdesc'),
        ),
        migrations.CreateModel(
            name='McyangTeacher',
            fields=[
                ('T_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('T_name', models.TextField(max_length=30)),
                ('T_email', models.CharField(max_length=50, unique=True)),
                ('T_password', models.TextField(max_length=50)),
                ('T_image', models.ImageField(upload_to='img_teacher/')),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mc_teacher',
                'unique_together': {('T_id', 'T_email')},
            },
        ),
        migrations.CreateModel(
            name='McyangSignRecord',
            fields=[
                ('SR_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangstudent')),
                ('Sign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangsign')),
            ],
            options={
                'db_table': 'mc_signrecord',
            },
        ),
        migrations.CreateModel(
            name='McyangRaceList',
            fields=[
                ('RL_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Answer', models.IntegerField(default=0)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('R_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangraceanswer')),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangstudent')),
            ],
            options={
                'db_table': 'mc_racelist',
            },
        ),
        migrations.CreateModel(
            name='McyangQuizTopic',
            fields=[
                ('QT_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('QT_doc', models.TextField(max_length=255)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangcourse')),
            ],
            options={
                'db_table': 'mc_quiztopic',
            },
        ),
        migrations.CreateModel(
            name='McyangQuizQuestion',
            fields=[
                ('QQ_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('QQ_title', models.TextField(max_length=255)),
                ('QQ_doc', models.TextField(max_length=255)),
                ('QQ_status', models.BooleanField(default=True)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('QT_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangquiztopic')),
            ],
            options={
                'db_table': 'mc_quizquestion',
            },
        ),
        migrations.CreateModel(
            name='McyangQuizAnswer',
            fields=[
                ('QA_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Answer_doc', models.TextField(max_length=255)),
                ('Answer', models.IntegerField(default=0)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('QQ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangquizquestion')),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangstudent')),
            ],
            options={
                'db_table': 'mc_answermember',
            },
        ),
        migrations.CreateModel(
            name='McyangCourseRecord',
            fields=[
                ('CR_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('crtTime', models.DateTimeField(auto_now_add=True)),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangcourse')),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangstudent')),
            ],
            options={
                'db_table': 'mc_courserecord',
            },
        ),
        migrations.AddField(
            model_name='mcyangcourse',
            name='T_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangteacher'),
        ),
    ]
