# Generated by Django 4.0.7 on 2022-09-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcyang', '0002_mcyangteamchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcyangteamchat',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
