# Generated by Django 4.0.7 on 2022-09-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcyang', '0003_mcyangteamchat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcyangteamchat',
            name='TeamLeader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcyang.mcyangteam'),
        ),
    ]
